/// Flutter icons DBIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DBIcons
///      fonts:
///       - asset: fonts/DBIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class DBIconss {
  DBIconss._();

  static const _kFontFam = 'DBIconss';
  static const _kFontPkg = null;

  static const IconData logoisotipo =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logoisotipo2 =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logoisotipo3 =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logoisotipo4 =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
